/* 🛸 20. Contato Alienígena História: Você está tentando se comunicar com um alien 
usando sinais booleanos. Desafio: let sinal1  true; let sinal2  false; Se ambos forem true, 
envie "Sinal de paz enviado 🛸 ", senão "Sem contato estabelecido*/

let sinal1 = true
let sinal2 = false

if(sinal1 && sinal2){
    console.log("Sinal de paz enviado")
}
else{
    console.log("Sem contato estabelecido")
}
